### ISSUE TITLE
Testcases fail

### ISSUE THREAD

**Issue by stefansiegl** [Appdynamics/rabbitmq-monitoring-extension#12]
Hi guys,

Just wanting to let you know that running the testcases result in an error. I had a brief look at it and it seems as if the expectedValueMap in `RabbitMqMonitoringTaskTest` does not contain the necessary entries.

Please have a look as a good test harness is the basis for contributions.

Thank you,
Stefan

Here is the output for `mvn clean install` on the current HEAD

[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.appdynamics.extensions:rabbitmq-monitoring-extension:jar:1.2.2
[WARNING] The expression ${build.directory} is deprecated. Please use ${project.build.directory} instead.
[WARNING] The expression ${build.directory} is deprecated. Please use ${project.build.directory} instead.
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building rabbitmq-monitoring-extension 1.2.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ rabbitmq-monitoring-extension ---
[INFO] Deleting /Users/stefan/work/Daimler/AppDynamics/rabbitmq-monitoring-extension/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rabbitmq-monitoring-extension ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ rabbitmq-monitoring-extension ---
[INFO] Compiling 7 source files to /Users/stefan/work/Daimler/AppDynamics/rabbitmq-monitoring-extension/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ rabbitmq-monitoring-extension ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ rabbitmq-monitoring-extension ---
[INFO] Compiling 1 source file to /Users/stefan/work/Daimler/AppDynamics/rabbitmq-monitoring-extension/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ rabbitmq-monitoring-extension ---
[INFO] Surefire report directory: /Users/stefan/work/Daimler/AppDynamics/rabbitmq-monitoring-extension/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTaskTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2017-12-07 09:12:39 INFO  RabbitMQMonitoringTaskTest:73 - Returning the mocked data for the api /json/nodes.json
2017-12-07 09:12:39 INFO  RabbitMQMonitoringTaskTest:73 - Returning the mocked data for the api /json/channels.json
2017-12-07 09:12:39 INFO  RabbitMQMonitoringTaskTest:73 - Returning the mocked data for the api /json/queues.json
"Nodes|rabbit@rabbit1|Channels|Blocked","0"
2017-12-07 09:12:39 INFO  RabbitMQMonitoringTaskTest:73 - Returning the mocked data for the api /json/nodes.json
2017-12-07 09:12:39 INFO  RabbitMQMonitoringTaskTest:73 - Returning the mocked data for the api /json/channels.json
2017-12-07 09:12:39 INFO  RabbitMQMonitoringTaskTest:73 - Returning the mocked data for the api /json/queues.json
"Nodes|rabbit@rabbit1|Channels|Blocked","0"
2017-12-07 09:12:39 INFO  RabbitMQMonitoringTaskTest:73 - Returning the mocked data for the api /json/nodes.json
2017-12-07 09:12:39 INFO  RabbitMQMonitoringTaskTest:73 - Returning the mocked data for the api /json/channels.json
2017-12-07 09:12:39 INFO  RabbitMQMonitoringTaskTest:73 - Returning the mocked data for the api /json/queues.json
"Nodes|rabbit@rabbit1|Channels|Blocked","0"
Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.522 sec <<< FAILURE!
testWithGroupsWithIndividual(com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTaskTest)  Time elapsed: 0.34 sec  <<< FAILURE!
java.lang.AssertionError: Unknown Metric Nodes|rabbit@rabbit1|Channels|Blocked
	at org.junit.Assert.fail(Assert.java:88)
	at com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTaskTest$1.answer(RabbitMQMonitoringTaskTest.java:55)
	at com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTaskTest.testWithGroupsWithIndividual(RabbitMQMonitoringTaskTest.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

checkReturnsFederationStatusWhenAvailable(com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTaskTest)  Time elapsed: 0.028 sec  <<< FAILURE!
java.lang.AssertionError: Unknown Metric Nodes|rabbit@rabbit1|Channels|Blocked
	at org.junit.Assert.fail(Assert.java:88)
	at com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTaskTest$1.answer(RabbitMQMonitoringTaskTest.java:55)
	at com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTaskTest.checkReturnsFederationStatusWhenAvailable(RabbitMQMonitoringTaskTest.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testWithGroupsNoIndividual(com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTaskTest)  Time elapsed: 0.022 sec  <<< FAILURE!
java.lang.AssertionError: Unknown Metric Nodes|rabbit@rabbit1|Channels|Blocked
	at org.junit.Assert.fail(Assert.java:88)
	at com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTaskTest$1.answer(RabbitMQMonitoringTaskTest.java:55)
	at com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTaskTest.testWithGroupsNoIndividual(RabbitMQMonitoringTaskTest.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Results :

Failed tests:   testWithGroupsWithIndividual(com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTaskTest): Unknown Metric Nodes|rabbit@rabbit1|Channels|Blocked
  checkReturnsFederationStatusWhenAvailable(com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTaskTest): Unknown Metric Nodes|rabbit@rabbit1|Channels|Blocked
  testWithGroupsNoIndividual(com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTaskTest): Unknown Metric Nodes|rabbit@rabbit1|Channels|Blocked

Tests run: 3, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.334 s
[INFO] Finished at: 2017-12-07T09:12:39+01:00
[INFO] Final Memory: 24M/304M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project rabbitmq-monitoring-extension: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/stefan/work/Daimler/AppDynamics/rabbitmq-monitoring-extension/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by akshayAppd** [comment]
All test cases have been fixed and work fine.
