### ISSUE TITLE
Extension crashes if federation plugin is not enabled

### ISSUE THREAD

**Issue by kfreem02** [Appdynamics/rabbitmq-monitoring-extension#17]
Request to add config option to bypass federation links.

[Monitor-Task-Thread1] 16 Feb 2018 16:11:11,670 ERROR RabbitMQMonitorTask - Error while fetching the '/api/federation-links' data, returning NULL
org.codehaus.jackson.map.JsonMappingException: Can not deserialize instance of org.codehaus.jackson.node.ArrayNode out of START_OBJECT token
 at [Source: java.io.StringReader@3f504833; line: 1, column: 1]
	at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163)
	at org.codehaus.jackson.map.deser.StdDeserializationContext.mappingException(StdDeserializationContext.java:219)
	at org.codehaus.jackson.map.deser.StdDeserializationContext.mappingException(StdDeserializationContext.java:212)
	at org.codehaus.jackson.map.deser.std.JsonNodeDeserializer$ArrayDeserializer.deserialize(JsonNodeDeserializer.java:116)
	at org.codehaus.jackson.map.deser.std.JsonNodeDeserializer$ArrayDeserializer.deserialize(JsonNodeDeserializer.java:98)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2725)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1856)
	at com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTask.getOptionalJson(RabbitMQMonitoringTask.java:219)
	at com.appdynamics.extensions.rabbitmq.RabbitMQMonitoringTask.run(RabbitMQMonitoringTask.java:157)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kunalgupApDx** [comment]
Yes. We will release a new build next week with the fix. 

@akshayAppd @satish-m

**Comment by akshayAppd** [comment]
The extension reports other metrics fine, and the logs only report the federation plugin not reporting metric. The latest version RabbitMq 2.0.0 handles ths in a better way.
